[package]
name = "ard_serial_comm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
serialport = "4.2.1"
libudev-sys = "0.1.4"

