[package]
name = "ard_serial_comm"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
serialport = "4.2.1"
time = {version="0.3.22", features=["macros"]}
chrono = "0.4.26"
csv = "1.2.2"
